### ISSUE TITLE
Missing default Country value leads to problems on first startup 

### ISSUE THREAD

**Issue by theimo1221** [Grizzelbee/ioBroker.dysonairpurifier#59] opened 2021-02-06 18:01 UTC
Hello Grizzelbee,

as my new Purifier arrived yesterday I'd like to connect it with IoBroker.
Unfortunately it seems like there is a problem during setup:
![image](https://user-images.githubusercontent.com/20605452/107126007-7cf51700-68ad-11eb-90c4-278d8b2d5fcc.png)

Do you think this is a network issue, or could it be some interference with special chars in my password (15+ chars)?

Best Regards

Thiemo

**Comment by Grizzelbee** [comment] 2021-02-06 19:59
Hi Thiemo,

as far as I can see in your log snippet the adapter is missing it's config or config isn't valid. Which meens that you need to give some additional config values to the adapter:
![grafik](https://user-images.githubusercontent.com/5459426/107128413-d82f0580-68bd-11eb-986b-9f6bf22462ff.png)

Please fill out the complete config and refer to the readme if there are questions - if readme dosen't claify all, please ask.
The dyson account the adapter asks for is the same which is used for the dyson mobile app.

**Comment by theimo1221** [comment] 2021-02-06 22:32
Thanks for the recommendations, as I'm using a password manager I'm not using german special chars.
I changed the password to numbers/chars only but still have the same issue as above

This is my config:
![image](https://user-images.githubusercontent.com/20605452/107131049-a163ea00-68d3-11eb-94f9-882a57283266.png)

**Comment by Grizzelbee** [comment] 2021-02-07 10:57
I'm pretty shure that it has nothing to do with your firewall/security gateway.

May I ask you to please switch the adapter to debug logging (Tab Instances ; expert mode) and post the log?
Best is to filter to the dysonairpurifier.0 instance before posting (most left column).

**Comment by Day1983** [comment] 2021-02-07 12:17
the same Problem - with 0.7. run the adapter, bute with 0.7.1 dosnt...

My tree is deleted

![image](https://user-images.githubusercontent.com/77491820/107146174-baf24980-6946-11eb-95ea-810a61b76364.png)

**Comment by Grizzelbee** [comment] 2021-02-07 12:46
AH! You ran 0.7.0 before?

Then please reenter the password in the config as mentioned in the readme and changelog.
I had to change something in the pwd-encryption routine.

That should solve your problem.

**Comment by mrtzlbm** [comment] 2021-02-07 14:21
Hi, I just had the same problem as @Day1983, however I did a fresh install of 0.7.1. I got the same errors as @Day1983. I had to change all adapter settings (including the preset ones) once. After restarting the adapter I got the adapter to show up in the object tree with the 'correct' errors. 👍
<img width="1446" alt="Bildschirmfoto 2021-02-07 um 15 18 50" src="https://user-images.githubusercontent.com/46360593/107149276-052ff680-6958-11eb-9ff5-4d2b85e53e03.png">

**Comment by Grizzelbee** [comment] 2021-02-07 16:15
Okay. Seems that we have two different things here:
1. Seems like I have messed up something with saving and loading of the config. This is not unlikely since I worked on it. I'll check it.
2. The green Part in @mrtzlbm 's Screenshot: Starting with V0.7.1 I try to connect to the device by it's serialnumber - which is also it's default hostname. This will work under two circumstances: 1. You have a FritzBox or you are running a dedicaed DNS in your LAN. 2. you haven't changed the default hostname of your device. If you can't answer all of these with YES - you'll need to enter the IP of your device since all the time before.

**Comment by mrtzlbm** [comment] 2021-02-07 18:25
@Grizzelbee I just hadn't set up the DNS record yet. Everything works fine for me, thanks :)
Just wanted to check in and describe how I got around the issue with the adapter config.

**Comment by Grizzelbee** [comment] 2021-02-08 12:40
@theimo1221 : Is your Issue also solved? Or arer you still struggeling?

**Comment by theimo1221** [comment] 2021-02-08 14:59
@Grizzelbee I'm still struggeling:
![image](https://user-images.githubusercontent.com/20605452/107236952-82c23800-6a26-11eb-857f-6cbbd6f77696.png)


If you want feel free to contact me directly in Discord, so I can share my screen/problem with you today evening

**Comment by viper4gh** [comment] 2021-02-09 09:06
I have the same problem with a fresh 0.7.1 installation, I configured username and password in the adapter config with the same result:
![2021-02-09_10-03-25__logs - ioBroker](https://user-images.githubusercontent.com/13273234/107340661-50fcb000-6abe-11eb-9ca6-1fe18750314a.jpg)

**Comment by Grizzelbee** [comment] 2021-02-09 10:23
@viper4gh, @theimo1221 
Okay. I'm just debugging the load/save config routines and enhancing the testConfig method. So please be patiend and wait for the upcoming version 0.7.2 - which should hopefully solve your problems. I'll keep you informed.

**Comment by theimo1221** [comment] 2021-02-09 20:18
@Grizzelbee Okay, I spotted the issue, it seems like the Country is `null`
I'll dig deeper

**Comment by theimo1221** [comment] 2021-02-09 20:33
By default country was empty while the browser selects "Deutschland" as the shown value for the country selection thus making the user believe country beeing correctly chosen.

Pull Request #61 resolves this.

**Comment by viper4gh** [comment] 2021-02-09 20:58
I can confirm, select the country again, solves this problem.
But now it stucks at the ip address.
I stopped the adapter, filled in the ip address at the Hostaddress datapoint in the device tree and started the adapter again.
Now the log still shows "No host address given. Trying to connect to the device with it's default hostname", which is not resolved by DNS in my case. 
Will do some tests tomorrow again, maybe I did something wrong.

**Comment by viper4gh** [comment] 2021-02-10 10:01
@Grizzelbee 
I reverted my workaround with the DNS Alias for the default Hostname to check, if the configured Hostaddress datapoint is working now after all data is received, but it is not.
That means the Hostaddress datapoint is still not read by the adapter and I get the log message "No host address given..." on startup.
Is there anything I need to pay special attention to for the ip address?

**Comment by Grizzelbee** [comment] 2021-02-10 14:37
@viper4gh What version are you on? Or in other Words: Have you tried 0.7.3 alredy? This should fix this issue.

**Comment by theimo1221** [comment] 2021-02-10 14:37
@Grizzelbee with newest version there might be an error regarding credentials
![image](https://user-images.githubusercontent.com/20605452/107524236-da42de00-6bb5-11eb-8438-f28dcb76c728.png)

**Comment by viper4gh** [comment] 2021-02-10 14:50
> @viper4gh What version are you on? Or in other Words: Have you tried 0.7.3 already? This should fix this issue.

I was still on 0.7.2, then I will test it with the new version and will give you feedback.

**Comment by Grizzelbee** [comment] 2021-02-10 14:51
@theimo1221 Please try to re-enter your password. There are some changes at this position which might lead to this.
Btw: Since I can't find the original question/conversation: Yes - your fix regarding the <select> has been deleted intentionally since we solved it in parallel and my fix changed more code. So it was the easiest way to drop only one line knowing the other code to work.

**Comment by theimo1221** [comment] 2021-02-10 15:11
@Grizzelbee I just changed my password on dyson.de and even with new password it doesn't work

On my ioBroker Server I get following response as well: `{"Message":"Unable to authenticate user."}`  so I don't know if I'm banned from the api
This was the request I made ` curl -X POST -H "Content-Type: application/json" -k 'https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=DE' -d '{"Email": "...", "Password": "..."}`

**Comment by viper4gh** [comment] 2021-02-10 15:12
I updated to 0.7.3, configured all settings again and now get the following:

![2021-02-10_16-08-13__logs - ioBroker](https://user-images.githubusercontent.com/13273234/107528747-77077a80-6bba-11eb-9b7c-fbf048252448.jpg)

It detects the controller 3.1.6, but says that the requirement of version 3.0.0. is not fulfilled.

**Comment by viper4gh** [comment] 2021-02-10 15:21
I completely uninstalled the adapter instance and the adapter, which uninstalls the device tree, too.
Then installed 0.7.3 again, configured all settings and now have the same problem as @theimo1221 : 

![2021-02-10_16-19-14__~capture](https://user-images.githubusercontent.com/13273234/107530272-ffd2e600-6bbb-11eb-8387-e338cbd1e1da.jpg)

**Comment by Grizzelbee** [comment] 2021-02-10 15:48
Grrrrr!! Seems to be a timing issue.
Facing it on my instances now as well where it worked first.

Sorry for that. Debugging ...

**Comment by theimo1221** [comment] 2021-02-10 16:15
What does this mean, are our accounts now rate limited, or is that a temporary thingy?

**Comment by Grizzelbee** [comment] 2021-02-10 16:30
> What does this mean, are our accounts now rate limited, or is that a temporary thingy?

I'm sorry - but currently I don't know. Debugging says: Credentials are okay. So it's no timing issue. My idea was, that the password is used for login before it is decryted. But thats not the case. Maybe dyson locked the adapter out. Or it's really a temporary thing. Let's wait a while and see what happens ...

**Comment by viper4gh** [comment] 2021-02-11 06:09
I tested the curl command again and still get:
{"Message":"Unable to authenticate user."}

It seems indeed we are now banned.
At least the Dyson Link app still works.

**Comment by Grizzelbee** [comment] 2021-02-11 10:54
> I tested the curl command again and still get: {"Message":"Unable to authenticate user."}

Same on my side in a few different tests.

> It seems indeed we are now banned.

I still don't believe really in being banned. The error message doesn't fit. But on the other hand I don't have any clue what really happend.

**Comment by theimo1221** [comment] 2021-02-11 18:13
Maybe the server tries to prevent unauthorized access by flagging those accounts which switched countries in a short tone frame

**Comment by viper4gh** [comment] 2021-02-12 08:28
After the adapter is working now with the workaround (https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/65#issuecomment-778047049) I can say that the adapter is using the configured Hostadress now, which was not working in my case before.

**Comment by Grizzelbee** [comment] 2021-02-12 15:28
Solved by PR https://github.com/Grizzelbee/ioBroker.dysonairpurifier/pull/66

**Closed by Grizzelbee** 2021-02-12 15:28 UTC
Labels: bug, documentation
